spring.application.name=todos
spring.datasource.url=jdbc:mysql://localhost:3306/Todo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sanvith@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=MySuperSecretKeyForJWTThatIsLongEnough123456